/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BinotypeSample {
    }
}
declare global {
    interface HTMLBinotypeSampleElement extends Components.BinotypeSample, HTMLStencilElement {
    }
    var HTMLBinotypeSampleElement: {
        prototype: HTMLBinotypeSampleElement;
        new (): HTMLBinotypeSampleElement;
    };
    interface HTMLElementTagNameMap {
        "binotype-sample": HTMLBinotypeSampleElement;
    }
}
declare namespace LocalJSX {
    interface BinotypeSample {
    }
    interface IntrinsicElements {
        "binotype-sample": BinotypeSample;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "binotype-sample": LocalJSX.BinotypeSample & JSXBase.HTMLAttributes<HTMLBinotypeSampleElement>;
        }
    }
}
